from dataclasses import dataclass
from typing import List

@dataclass
class CrawlerHardcodedConfig:
  PERSISTENT_STORAGE_PATH_DOMAINS_SUBFOLDER: str
  PERSISTENT_STORAGE_PATH_CRAWLER_SUBFOLDER: str
  PERSISTENT_STORAGE_PATH_LOGS_SUBFOLDER: str
  PERSISTENT_STORAGE_PATH_DOCUMENTS_FOLDER: str
  PERSISTENT_STORAGE_PATH_LISTS_FOLDER: str
  PERSISTENT_STORAGE_PATH_SITEPAGES_FOLDER: str
  PERSISTENT_STORAGE_PATH_ORIGINALS_SUBFOLDER: str
  PERSISTENT_STORAGE_PATH_EMBEDDED_SUBFOLDER: str
  PERSISTENT_STORAGE_PATH_FAILED_SUBFOLDER: str
  UNZIP_TO_PERSISTENT_STORAGE_IF_NEWER: str
  UNZIP_TO_PERSISTENT_STORAGE_OVERWRITE: str
  UNZIP_TO_PERSISTENT_STORAGE_CLEAR_BEFORE: str
  LOCALSTORAGE_ZIP_FILENAME_PREFIX: str
  DEFAULT_FILETYPES_ACCEPTED_BY_VECTOR_STORES: List[str]



CRAWLER_HARDCODED_CONFIG = CrawlerHardcodedConfig(
  PERSISTENT_STORAGE_PATH_DOMAINS_SUBFOLDER="domains"
  ,PERSISTENT_STORAGE_PATH_CRAWLER_SUBFOLDER="crawler"
  ,PERSISTENT_STORAGE_PATH_LOGS_SUBFOLDER="logs"
  ,PERSISTENT_STORAGE_PATH_DOCUMENTS_FOLDER="01_files"
  ,PERSISTENT_STORAGE_PATH_LISTS_FOLDER="02_lists"
  ,PERSISTENT_STORAGE_PATH_SITEPAGES_FOLDER="03_sitepages"
  ,PERSISTENT_STORAGE_PATH_ORIGINALS_SUBFOLDER="01_originals"
  ,PERSISTENT_STORAGE_PATH_EMBEDDED_SUBFOLDER="02_embedded"
  ,PERSISTENT_STORAGE_PATH_FAILED_SUBFOLDER="03_failed"
  ,UNZIP_TO_PERSISTENT_STORAGE_IF_NEWER=".unzip_to_persistant_storage_if_newer"
  ,UNZIP_TO_PERSISTENT_STORAGE_OVERWRITE=".unzip_to_persistant_storage_overwrite"
  ,UNZIP_TO_PERSISTENT_STORAGE_CLEAR_BEFORE=".unzip_to_persistant_storage_clear_before"
  ,LOCALSTORAGE_ZIP_FILENAME_PREFIX="download_"
  # https://platform.openai.com/docs/assistants/tools/file-search/supported-files#supported-files
  ,DEFAULT_FILETYPES_ACCEPTED_BY_VECTOR_STORES=["c", "cpp", "cs", "css", "doc", "docx", "go", "html", "java", "js", "json", "md", "pdf", "php", "pptx", "py", "rb", "sh", "tex", "ts", "txt"]
)
