from dataclasses import dataclass

@dataclass
class CrawlerHardcodedConfig:
  PERSISTENT_STORAGE_PATH_DOMAINS_SUBFOLDER: str
  UNZIP_TO_PERSISTENT_STORAGE_IF_NEWER: str
  UNZIP_TO_PERSISTENT_STORAGE_OVERWRITE: str
  UNZIP_TO_PERSISTENT_STORAGE_CLEAR_BEFORE: str
  LOCALSTORAGE_ZIP_FILENAME_PREFIX: str

CRAWLER_HARDCODED_CONFIG = CrawlerHardcodedConfig(
  PERSISTENT_STORAGE_PATH_DOMAINS_SUBFOLDER="domains"
  ,UNZIP_TO_PERSISTENT_STORAGE_IF_NEWER=".unzip_to_persistant_storage_if_newer"
  ,UNZIP_TO_PERSISTENT_STORAGE_OVERWRITE=".unzip_to_persistant_storage_overwrite"
  ,UNZIP_TO_PERSISTENT_STORAGE_CLEAR_BEFORE=".unzip_to_persistant_storage_clear_before"
  ,LOCALSTORAGE_ZIP_FILENAME_PREFIX="download_"
)
